# Generated by Django 4.2 on 2025-11-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название элемента')),
                ('element_type', models.CharField(choices=[('windshield', 'Лобовое стекло'), ('front_side', 'Передние боковые'), ('rear_side', 'Задние боковые'), ('rear_window', 'Заднее стекло'), ('headlights', 'Фары'), ('taillights', 'Задние фонари'), ('full_car', 'Полный автомобиль')], max_length=20, verbose_name='Тип элемента')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код элемента')),
            ],
            options={
                'verbose_name': 'Элемент автомобиля',
                'verbose_name_plural': 'Элементы автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.carbrand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('tinting', 'Тонировка'), ('armor', 'Бронирование'), ('both', 'Тонировка + Бронирование')], max_length=20, verbose_name='Тип услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.carmodel', verbose_name='Модель автомобиля')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.carelement', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Настройка цены',
                'verbose_name_plural': 'Настройки цен',
                'unique_together': {('car_model', 'element', 'service_type')},
            },
        ),
    ]
