# Generated by Django 4.2 on 2025-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='base_price',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='protect',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Полная бронь'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='tinting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Полная тонировка'),
        ),
    ]
