# Generated by Django 4.2 on 2025-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_carmodel_base_price_carmodel_protect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelement',
            name='element_type',
            field=models.CharField(max_length=20, verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='service_type',
            field=models.CharField(choices=[('tinting', 'Тонировка'), ('armor', 'Бронирование')], max_length=20, verbose_name='Тип услуги'),
        ),
    ]
