# Generated by Django 4.2 on 2025-11-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_carelement_element_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя мастера')),
                ('phone', models.IntegerField(max_length=11, verbose_name='Номер телефона')),
                ('e_mail', models.CharField(max_length=255, verbose_name='email')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('time_w', models.CharField(max_length=255, verbose_name='Часы работы')),
            ],
        ),
    ]
