# Generated by Django 4.2 on 2025-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='protect',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='tinting',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая наценка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Номер телефона'),
        ),
    ]
