# Generated by Django 4.2 on 2025-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_carmodel_protect_remove_carmodel_tinting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='prot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Повышение цены'),
        ),
    ]
