# Generated by Django 4.2 on 2025-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_carmodel_prot_alter_carmodel_price_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='prot',
        ),
    ]
